/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.unicolombo.pb.ventanas;

import co.edu.unicolombo.pb.entidades.Convocatoria;
import static co.edu.unicolombo.pb.entidades.Convocatoria.convocatorias;
import co.edu.unicolombo.pb.entidades.Empresa;
import co.edu.unicolombo.pb.entidades.UsuarioEm;
import co.edu.unicolombo.pb.persistencia.Almacenamiento;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Jesus Ramos
 */
public class VentanaRegistroConvocatorias extends javax.swing.JFrame {

    /**
     * Creates new form VentanaRegistroConvocatorias
     */
    public VentanaRegistroConvocatorias() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        campoFechaFin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        campoFechaInicio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        campoSueldo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        campoNumero = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        campoVacante = new javax.swing.JTextField();
        btnCrearConvocatoria = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Fecha Fin:");

        jLabel2.setText("Fecha Inicio:");

        jLabel3.setText("Sueldo aprox:");

        jLabel7.setText("Numero:");

        campoNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNumeroActionPerformed(evt);
            }
        });

        jLabel8.setText("Vacante:");

        btnCrearConvocatoria.setText("Crear Convocatoria");
        btnCrearConvocatoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearConvocatoriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCrearConvocatoria)
                .addGap(94, 94, 94))
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel3)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(campoNumero, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                    .addComponent(campoVacante, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoFechaInicio, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoFechaFin, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoSueldo, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(campoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(campoFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(campoVacante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(campoSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83)
                .addComponent(btnCrearConvocatoria)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNumeroActionPerformed

    private void btnCrearConvocatoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearConvocatoriaActionPerformed
        try {
            // Recuperar empresas desde el almacenamiento
            Empresa.empresas = Almacenamiento.recuperarE();
            System.out.println("Usuarios recuperados: " + Empresa.empresas);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al recuperar empresas: " + ex.getMessage());
            return;
        }

        SimpleDateFormat formatoFecha = new SimpleDateFormat("dd-MM-yyyy");

        int numero = Integer.parseInt(campoNumero.getText());
        String vacante = campoVacante.getText();
        String sueldo = campoSueldo.getText();
        Date fechaInicio = null;
        Date fechaFin = null;
        try {
            fechaInicio = formatoFecha.parse(campoFechaInicio.getText());
            fechaFin = formatoFecha.parse(campoFechaFin.getText());
        } catch (ParseException ex) {
            Logger.getLogger(VentanaRegistroConvocatorias.class.getName()).log(Level.SEVERE, null, ex);
        }

        String correo = PerfilEmpresa.etqCorreo.getText();
        if (Empresa.empresas.containsKey(correo)) {
            Empresa e = Empresa.empresas.get(correo);

            // Crear una nueva convocatoria
            Convocatoria convocatoria = new Convocatoria(numero, fechaInicio, fechaFin, vacante, sueldo);
            convocatoria.numero = numero;
            convocatoria.Fecha_Inicio = fechaInicio;
            convocatoria.Fecha_Fin = fechaFin;
            convocatoria.Vacante = vacante;
            convocatoria.Sueldo = sueldo;
            Convocatoria.convocatorias.put(numero, convocatoria);
            System.out.println("Numero de la convocatoria a crear: " + numero);
            Empresa.empresas.put(correo, e);
            e.crearConvocatoria(numero, fechaInicio, fechaFin, vacante, sueldo);
           
            System.out.println("Convocatoria asociada a la empresa: " + e);
            try {
                Almacenamiento.guardarConvocatorias(Convocatoria.convocatorias);
                JOptionPane.showMessageDialog(this, "Registrado con éxito...");
            } catch (IOException error) {
                JOptionPane.showMessageDialog(this, error.getMessage());
            }

        } else {
            JOptionPane.showMessageDialog(this, "La empresa con el correo proporcionado no existe.");
        }
        setVisible(false);

    }//GEN-LAST:event_btnCrearConvocatoriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroConvocatorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroConvocatorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroConvocatorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroConvocatorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaRegistroConvocatorias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearConvocatoria;
    private javax.swing.JTextField campoFechaFin;
    private javax.swing.JTextField campoFechaInicio;
    private javax.swing.JTextField campoNumero;
    private javax.swing.JTextField campoSueldo;
    private javax.swing.JTextField campoVacante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
